//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntryPoint.WebApi.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EntryPoint.WebApi.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request received is invalid. Check the format and the parameters in the documentation, correct them and try again..
        /// </summary>
        internal static string CommonInvalidRequest {
            get {
                return ResourceManager.GetString("CommonInvalidRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property &apos;{0}&apos; is invalid..
        /// </summary>
        internal static string CommonJsonPropertyInvalid {
            get {
                return ResourceManager.GetString("CommonJsonPropertyInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property &apos;{0}&apos; is required..
        /// </summary>
        internal static string CommonJsonPropertyMissing {
            get {
                return ResourceManager.GetString("CommonJsonPropertyMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property &apos;{0}&apos; has a value not compatible with it&apos;s expected type..
        /// </summary>
        internal static string CommonJsonPropertyWrongType {
            get {
                return ResourceManager.GetString("CommonJsonPropertyWrongType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error has occurred, please try again later!.
        /// </summary>
        internal static string CommonUnexpectedException {
            get {
                return ResourceManager.GetString("CommonUnexpectedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error has occurred, please try again later! Details: {0}..
        /// </summary>
        internal static string CommonUnexpectedExceptionWithParams {
            get {
                return ResourceManager.GetString("CommonUnexpectedExceptionWithParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please correct the errors and send your information again!.
        /// </summary>
        internal static string CommonValidationAlert {
            get {
                return ResourceManager.GetString("CommonValidationAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;ai settings&apos; is missing..
        /// </summary>
        internal static string ValidationAiSettingsIsNull {
            get {
                return ResourceManager.GetString("ValidationAiSettingsIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;API Key&apos; is mandatory when AI is enabled..
        /// </summary>
        internal static string ValidationApiKeyIsNullOrEmpty {
            get {
                return ResourceManager.GetString("ValidationApiKeyIsNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required client identifier is missing..
        /// </summary>
        internal static string ValidationClientUidIsNullOrEmpty {
            get {
                return ResourceManager.GetString("ValidationClientUidIsNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required client description is missing..
        /// </summary>
        internal static string ValidationDescriptionIsNullOrEmpty {
            get {
                return ResourceManager.GetString("ValidationDescriptionIsNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The max tokens exceeds the limit..
        /// </summary>
        internal static string ValidationMaxTokensExceedsLimit {
            get {
                return ResourceManager.GetString("ValidationMaxTokensExceedsLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The max tokens exceeds is not integer..
        /// </summary>
        internal static string ValidationMaxTokensIsNotInteger {
            get {
                return ResourceManager.GetString("ValidationMaxTokensIsNotInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The max tokens exceeds is missing..
        /// </summary>
        internal static string ValidationMaxTokensIsNullOrEmpty {
            get {
                return ResourceManager.GetString("ValidationMaxTokensIsNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The model is missing..
        /// </summary>
        internal static string ValidationModelIsNullOrEmpty {
            get {
                return ResourceManager.GetString("ValidationModelIsNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required client name is missing..
        /// </summary>
        internal static string ValidationNameIsNullOrEmpty {
            get {
                return ResourceManager.GetString("ValidationNameIsNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;prompt template&apos; is missing..
        /// </summary>
        internal static string ValidationPromptTemplateIsNullOrEmpty {
            get {
                return ResourceManager.GetString("ValidationPromptTemplateIsNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;query name&apos; is missing..
        /// </summary>
        internal static string ValidationQueryNameIsNullOrEmpty {
            get {
                return ResourceManager.GetString("ValidationQueryNameIsNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No query structure was found with client uid {0} and query name {1}..
        /// </summary>
        internal static string ValidationQueryStructureByClientAndNameNotFound {
            get {
                return ResourceManager.GetString("ValidationQueryStructureByClientAndNameNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;search term&apos; is missing..
        /// </summary>
        internal static string ValidationSearchTermsIsNullOrEmpty {
            get {
                return ResourceManager.GetString("ValidationSearchTermsIsNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;temperature&apos; is not a valid float number..
        /// </summary>
        internal static string ValidationTemperatureIsNotFloat {
            get {
                return ResourceManager.GetString("ValidationTemperatureIsNotFloat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;temperature&apos; is missing..
        /// </summary>
        internal static string ValidationTemperatureIsNullOrEmpty {
            get {
                return ResourceManager.GetString("ValidationTemperatureIsNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;percentage&apos; is not a valid percentage..
        /// </summary>
        internal static string ValidationUsagePercentageIsNotPercentage {
            get {
                return ResourceManager.GetString("ValidationUsagePercentageIsNotPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;percentage&apos; is missing..
        /// </summary>
        internal static string ValidationUsagePercentageIsNullOrEmpty {
            get {
                return ResourceManager.GetString("ValidationUsagePercentageIsNullOrEmpty", resourceCulture);
            }
        }
    }
}
